### ISSUE TITLE
powermgmt not applying settings

### ISSUE THREAD

**Issue by nlscott** [mosen/puppet-osx-powermgmt#1]
I'll admit, I'm fairly new to puppet, so forgive me if this comes off as obvious. I'm never installed a module that isn't from the forgue. So I assume I can just download "puppet-osx-powermgmt", unpack it and copy it to  "/etc/puppet/modules" on my Master.

Then I added this to my node.pp. Just to test one setting.

  powermgmt { "charger":
                  sleep      => 0,
                  }

When I run "puppet agent --test" on my node, Puppet spits this out:
Nov 11 15:54:12 k109199.local puppet-agent[1905]: (/Stage[main]/Main/Node[k109199]/Powermgmt[charger]/display_sleep) display_sleep changed '30' to '10'
Nov 11 15:54:12 k109199.local puppet-agent[1905]: (/Stage[main]/Main/Node[k109199]/Powermgmt[charger]/disk_sleep) disk_sleep changed '0' to '10'
Nov 11 15:54:12 k109199.local puppet-agent[1905]: (/Stage[main]/Main/Node[k109199]/Powermgmt[charger]/wake_on_lan) wake_on_lan changed '' to 'true'
Nov 11 15:54:12 k109199.local puppet-agent[1905]: (/Stage[main]/Main/Node[k109199]/Powermgmt[charger]/autorestart) autorestart changed '' to 'true'
Nov 11 15:54:13 k109199.local puppet-agent[1905]: (/Stage[main]/Main/Node[k109199]/Powermgmt[charger]/power_button_sleeps) power_button_sleeps changed '' to 'true'

I didn't even set anything for "disk_sleep" or "wake_on_lan" ... just "sleep'. And the power settings never change even after a restart. When I run puppet agent --test, again, I get the same results.

I'm hoping I'm missing something very basic and easy to fix?

![screen shot 2014-11-11 at 4 08 06 pm](https://cloud.githubusercontent.com/assets/3018699/5000777/01f67a80-69bd-11e4-8328-e446a4de784d.png)

**Comment by mosen** [comment]
Hi there,
Sorry about the delay.

You are correct in that there is a problem. The module is no longer picking up the name of the power source which must have changed behavior due to a puppet upgrade probably.

I'm looking into a quick fix so that it correctly recognizes the "charger", "battery" etc.. sources again.

m

**Comment by mosen** [comment]
Please check out the latest master and see if that is working better for you.
m.
